<?php
/**
 * @file
 * Code for the Studio Feeds feature.
 */

include_once 'studio_feeds.features.inc';

/**
 * Implements template_preprocess_views_view().
 */
function studio_feeds_preprocess_views_view(&$variables) {
  $view = $variables['view'];

  // Prepend the newsroom articles to newsroom view.
  if ($view->name == 'newsroom' && $view->current_display == 'newsroom') {
    $newsroom_articles = views_embed_view('newsroom_articles', 'newsroom_articles');
    $variables['rows'] = $newsroom_articles . $variables['rows'];
  }
}
