<?php
/**
 * @file
 * Code for the Studio Programs feature.
 */

include_once 'studio_programs.features.inc';


function studio_programs_preprocess_views_view(&$vars) {
  
  $view = &$vars['view'];
  
  $header_nav_views = array(
    'program_examples',
    'project_examples',
  );
  
  if (in_array($view->name, $header_nav_views)) {
    
    drupal_add_js(array('studio_programs' => array('header_nav_view' => 'view-'. str_replace('_', '-', $view->name))), 'setting');
    drupal_add_js(drupal_get_path('module', 'studio_programs') .'/js/studio_programs.view_nav_and_previews.js', 'file');
    
    $view_header_anchors = array();
    
    $view_header_anchors[] = '<a href="#section-all" class="program-examples-view-header-anchor">All</a>';
    
    foreach (taxonomy_get_tree(SECTIONS_VID, 0, NULL, TRUE) as $key => $term) {
      
      $term_country_field = field_get_items('taxonomy_term', $term, 'field_country');
      
      $term_country_icon_vars = array('code' => $term_country_field[0]['iso2']);
      
      dpm('icon vars');
      dpm($term_country_icon_vars);
      
      $term_country_icon = theme_countryicons_icon($term_country_icon_vars);
      
      $view_header_anchors[] = '<a href="#section-'. $term->tid .'" class="program-examples-view-header-anchor">'. $term->name . $term_country_icon .'</a>';
    }
    
    $view_header = '<div class="program-examples-view-header">View: '. implode(' &nbsp;|&nbsp; ', $view_header_anchors) .'</div>';
    
    $vars['attachment_before'] .= $view_header;
  }
}
